name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.13

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install flake8 bandit

    - name: Lint with flake8
      run: |
        flake8 src/ --max-line-length=100

    - name: Bandit scan
      run: |
        bandit -r src/ --severity-level high

    - name: Build Docker image
      if: ${{ success() }}
      run: |
        docker build -t mon-app:latest .

    - name: Docker Scout
      run: |
        docker scout quickview mon-app:latest